name: Docker build/run CI

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
    
jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build
        run: docker build -t screen -f screen/Dockerfile .
      
      - name: Run
        run: docker run -d -p 0:0 screen

